services:
  circus-racing:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1959:1959"
    env_file: .env
    volumes:
      - circus-db:/app/db
    restart: unless-stopped

volumes:
  circus-db:
