services:
  circus-racing:
    image: ghcr.io/kehnte/circus-racing-server:latest
    ports:
      - "1959:1959"
    env_file: .env
    volumes:
      - circus-db:/app/db
    restart: unless-stopped

volumes:
  circus-db:
